remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
logo: /img/OAuth2OOo.png
title: OAuth2OOo
description: OAuth2.0 protocol, Python Requests and Selenium in a single LibreOffice extension
show_downloads: true
github:
  zip_url: https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt
