remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
favicon: true
logo: /img/OAuth2OOo.png
title: OAuth2OOo
description: The OAuth2.0 protocol, Python Requests and Selenium in a single LibreOffice extension
sidebar:
  - name: Extension download
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/prrvchr
