remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [OAuth2OOo libreOffice extension]
description: [Auth2 protocol and Python Request in a single extension]
