#ifndef __com_sun_star_auth_XOAuth2Service_idl__
#define __com_sun_star_auth_XOAuth2Service_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/auth/RestRequestParameter.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/beans/Optional.idl>
#include <com/sun/star/io/XInputStream.idl>
#include <com/sun/star/io/XOutputStream.idl>
#include <com/sun/star/container/XEnumeration.idl>
#include <com/sun/star/sdbc/XConnection.idl>
#include <com/sun/star/logging/XLogger.idl>

module com { module sun { module star { module auth {

interface XOAuth2Service: com::sun::star::uno::XInterface
{

    void initializeSession([in] string ResourceUrl);
    boolean initializeUser([in] string UserName);
    boolean getAuthorization([in] string ResourceUrl,
                             [in] string UserName,
                             [in] boolean AutoClose);
    void logp([in] long Level,
              [in] string Source,
              [in] string Method,
              [in] string Message);
    ::com::sun::star::auth::XRestKeyMap getKeyMap();
    short getSessionMode([in] string Host);
    string getToken([in] string Format);
    ::com::sun::star::beans::Optional<::com::sun::star::auth::XRestKeyMap> execute([in] RestRequestParameter Parameter);
    ::com::sun::star::container::XEnumeration getEnumerator([in] RestRequestParameter Parameter);
    ::com::sun::star::io::XInputStream getInputStream([in] RestRequestParameter Parameter,
                                                      [in] long Chunk,
                                                      [in] long Buffer);
    ::com::sun::star::uno::XInterface getUploader([in] ::com::sun::star::uno::XInterface DataSource);

    [attribute, readonly] ::com::sun::star::uno::XInterface Setting;
    [attribute, readonly] ::com::sun::star::uno::XInterface Session;
    [attribute, readonly] ::com::sun::star::logging::XLogger Logger;
    [attribute] string ResourceUrl;
    [attribute] string UserName;
    [attribute] string Error;

};


}; }; }; };

#endif
