# .github/workflows/fascan.yml
name: Fluid Attacks Scan
on: [push, pull_request, workflow_dispatch]
jobs:
  machineStandalone:
    name: machineStandalone job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: docker://docker.io/fluidattacks/cli:latest
        name: machineStandalone
        with:
          args: skims scan ./_fascan.yml